// Generated by gencpp from file assignment/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_MESSAGE_ADDTWOINTS_H
#define ASSIGNMENT_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <assignment/AddTwoIntsRequest.h>
#include <assignment/AddTwoIntsResponse.h>


namespace assignment
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace assignment


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment::AddTwoInts > {
  static const char* value()
  {
    return "95fe1f9a1a908e906775b69d5fe39edf";
  }

  static const char* value(const ::assignment::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::assignment::AddTwoInts > {
  static const char* value()
  {
    return "assignment/AddTwoInts";
  }

  static const char* value(const ::assignment::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::assignment::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::assignment::AddTwoInts > 
template<>
struct MD5Sum< ::assignment::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment::AddTwoInts >::value();
  }
  static const char* value(const ::assignment::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment::AddTwoIntsRequest> should match 
// service_traits::DataType< ::assignment::AddTwoInts > 
template<>
struct DataType< ::assignment::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::assignment::AddTwoInts >::value();
  }
  static const char* value(const ::assignment::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::assignment::AddTwoInts > 
template<>
struct MD5Sum< ::assignment::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment::AddTwoInts >::value();
  }
  static const char* value(const ::assignment::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment::AddTwoIntsResponse> should match 
// service_traits::DataType< ::assignment::AddTwoInts > 
template<>
struct DataType< ::assignment::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::assignment::AddTwoInts >::value();
  }
  static const char* value(const ::assignment::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_MESSAGE_ADDTWOINTS_H
