// Generated by gencpp from file assignment/ultrasound_2.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_MESSAGE_ULTRASOUND_2_H
#define ASSIGNMENT_MESSAGE_ULTRASOUND_2_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment
{
template <class ContainerAllocator>
struct ultrasound_2_
{
  typedef ultrasound_2_<ContainerAllocator> Type;

  ultrasound_2_()
    : b()
    , a()  {
    }
  ultrasound_2_(const ContainerAllocator& _alloc)
    : b(_alloc)
    , a(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _b_type;
  _b_type b;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _a_type;
  _a_type a;




  typedef boost::shared_ptr< ::assignment::ultrasound_2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment::ultrasound_2_<ContainerAllocator> const> ConstPtr;

}; // struct ultrasound_2_

typedef ::assignment::ultrasound_2_<std::allocator<void> > ultrasound_2;

typedef boost::shared_ptr< ::assignment::ultrasound_2 > ultrasound_2Ptr;
typedef boost::shared_ptr< ::assignment::ultrasound_2 const> ultrasound_2ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment::ultrasound_2_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment::ultrasound_2_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assignment

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'assignment': ['/home/raghunath/catkin_ws/src/assignment/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assignment::ultrasound_2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment::ultrasound_2_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment::ultrasound_2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment::ultrasound_2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment::ultrasound_2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment::ultrasound_2_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment::ultrasound_2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6903e7caf1ccb729fc400b6c391325a3";
  }

  static const char* value(const ::assignment::ultrasound_2_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6903e7caf1ccb729ULL;
  static const uint64_t static_value2 = 0xfc400b6c391325a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment::ultrasound_2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment/ultrasound_2";
  }

  static const char* value(const ::assignment::ultrasound_2_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment::ultrasound_2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string b\n\
string a\n\
";
  }

  static const char* value(const ::assignment::ultrasound_2_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment::ultrasound_2_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.b);
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ultrasound_2_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment::ultrasound_2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment::ultrasound_2_<ContainerAllocator>& v)
  {
    s << indent << "b: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.b);
    s << indent << "a: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_MESSAGE_ULTRASOUND_2_H
